## Numpy

In [1]:
import numpy as np

In [3]:
myarr=np.array([1,2,3,4],np.float64)

In [4]:
myarr

array([1., 2., 3., 4.])

In [5]:
myarr.shape

(4,)

In [6]:
myarr.size

4

In [7]:
myarr.dtype

dtype('float64')

In [10]:
zeroes=np.zeros((5,4))
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
rng=np.arange(17)

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
lspace=np.linspace(1,9,5)

In [14]:
lspace

array([1., 3., 5., 7., 9.])

In [15]:
lspace.dtype

dtype('float64')

In [16]:
lspace.size

5

In [17]:
lspace.shape

(5,)

In [18]:
lspace2=np.linspace(1,9)

In [19]:
lspace2

array([1.        , 1.16326531, 1.32653061, 1.48979592, 1.65306122,
       1.81632653, 1.97959184, 2.14285714, 2.30612245, 2.46938776,
       2.63265306, 2.79591837, 2.95918367, 3.12244898, 3.28571429,
       3.44897959, 3.6122449 , 3.7755102 , 3.93877551, 4.10204082,
       4.26530612, 4.42857143, 4.59183673, 4.75510204, 4.91836735,
       5.08163265, 5.24489796, 5.40816327, 5.57142857, 5.73469388,
       5.89795918, 6.06122449, 6.2244898 , 6.3877551 , 6.55102041,
       6.71428571, 6.87755102, 7.04081633, 7.20408163, 7.36734694,
       7.53061224, 7.69387755, 7.85714286, 8.02040816, 8.18367347,
       8.34693878, 8.51020408, 8.67346939, 8.83673469, 9.        ])

In [20]:
lspace2.size


50

In [21]:
emp=np.empty((3,4))
emp

array([[1.50667803e-312, 0.00000000e+000, 8.76794447e+252,
        2.15895723e+227],
       [6.48224638e+170, 3.67145870e+228, 7.58253645e-096,
        9.03292329e+271],
       [9.08366793e+223, 1.41075687e+232, 1.16070543e-028,
        4.05919345e-317]])

In [22]:
emp_like=np.empty_like(lspace2)
emp_like

array([1.        , 1.16326531, 1.32653061, 1.48979592, 1.65306122,
       1.81632653, 1.97959184, 2.14285714, 2.30612245, 2.46938776,
       2.63265306, 2.79591837, 2.95918367, 3.12244898, 3.28571429,
       3.44897959, 3.6122449 , 3.7755102 , 3.93877551, 4.10204082,
       4.26530612, 4.42857143, 4.59183673, 4.75510204, 4.91836735,
       5.08163265, 5.24489796, 5.40816327, 5.57142857, 5.73469388,
       5.89795918, 6.06122449, 6.2244898 , 6.3877551 , 6.55102041,
       6.71428571, 6.87755102, 7.04081633, 7.20408163, 7.36734694,
       7.53061224, 7.69387755, 7.85714286, 8.02040816, 8.18367347,
       8.34693878, 8.51020408, 8.67346939, 8.83673469, 9.        ])

In [23]:
ide=np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# IMP reshape

In [24]:
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
arr.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
arr=arr.reshape(4,25)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
arr1=arr.ravel()
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [35]:
arr1[9]=100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [37]:
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8, 100,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [38]:
arr2=arr.flatten()
arr2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [39]:
arr2[10]=9092
arr2

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,  100, 9092,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99])

In [40]:
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8, 100,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [41]:
li=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(li)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ar.sum()

45

In [43]:
ar.sum(axis=0)

array([12, 15, 18])

In [44]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
lspace.T.shape

(5,)

In [47]:
lspace

array([1., 3., 5., 7., 9.])

In [49]:
ar.ndim

2

In [50]:
lspace.ndim


1

In [51]:
lspace.nbytes


40

In [52]:
ar.nbytes


36

In [57]:
on=np.array([1,12,90,-110,78])
on.argmax()

2

In [54]:
on.argmin()

3

In [56]:
on.argsort()

array([3, 0, 1, 4, 2], dtype=int32)

In [60]:
z=np.array([[1,2,3],[4,5,6],[7,1,0]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
print(z.argmax())
print(z.argmin())

6
8


In [62]:
z.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [63]:
z.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

In [64]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
z.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [82]:
a1=np.array([[1,2,3],[4,5,6],[1,8,9]])
a2=np.array([[3,8,1],[7,9,4],[0,6,2]])
a1+a2

array([[ 4, 10,  4],
       [11, 14, 10],
       [ 1, 14, 11]])

In [75]:
a1*a2

array([[ 3, 16,  3],
       [28, 45, 24],
       [ 0, 48, 18]])

In [76]:
a1-a2

array([[-2, -6,  2],
       [-3, -4,  2],
       [ 7,  2,  7]])

In [78]:
a1.min()

1

In [79]:
a1.argmin()

0

In [80]:
a1.max()

9

In [81]:
a1.argmax()

8

In [83]:
a1.min()

1

In [84]:
a1.argmin()

0

In [85]:
a1.min(axis=0)

array([1, 2, 3])

In [86]:
a1.sum(axis=0)

array([ 6, 15, 18])

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [89]:
np.where(z>10)

(array([], dtype=int32), array([], dtype=int32))

In [99]:
b=np.where(z>3)

In [92]:
np.where(z>5)

In [96]:
z[b]

array([4, 5, 6, 7])

In [100]:
z[1][2]=-1100
z[b]

array([4, 5, 7])

In [101]:
z

array([[    1,     2,     3],
       [    4,     5, -1100],
       [    7,     1,     0]])

In [102]:
np.count_nonzero(z)

8

In [104]:
np.size(ar)

9

In [105]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
ar.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [108]:
z

array([[    1,     2,     3],
       [    4,     5, -1100],
       [    7,     1,     0]])

In [109]:
z.itemsize*z.size


36

In [110]:
z.itemsize

4